builder: Ensure builder user before /srv/builder/.npm
Follows-up 89559bce568b67e54bb082815950779ecb837482.

It works fine after a re-run and I won't be able to test this until the
next provision, but this might do the trick.

```
$ bin/provision-instance.sh builder-03.ops.jquery.net production
…
Info: Downloaded certificate for builder-03.ops.jquery.net from https://puppet-04.ops.jquery.net:8140/puppet-ca/v1
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
…
Notice: Requesting catalog from puppet-04.ops.jquery.net:8140 (167.172.21.26)
Info: Caching catalog for builder-03.ops.jquery.net
Info: Applying configuration version '(c7c5110) Timo Tijhof - site: add builder-03 and builder-06.stage'
…
Notice: /Stage[main]/Users::Config/File[/etc/adduser.conf]/…
…
Notice: /Stage[main]/Notifier/File[/etc/notifier.d/]/ensure: created
Info: /Stage[main]/Notifier/File[/etc/notifier.d/]: Scheduling refresh of Service[notifier]
Notice: /Stage[main]/Profile::Builder/File[/srv/builder]/ensure: created
Error: Could not set 'directory' on ensure: Could not find user builder (file: /etc/puppet/code/environments/production/modules/profile/manifests/builder.pp, line: 30)
Error: Could not set 'directory' on ensure: Could not find user builder (file: /etc/puppet/code/environments/production/modules/profile/manifests/builder.pp, line: 30)
Wrapped exception:
Could not find user builder
Error: /Stage[main]/Profile::Builder/File[/srv/builder/.npm]/ensure: change from 'absent' to 'directory' failed: Could not set 'directory' on ensure: Could not find user builder (file: /etc/puppet/code/environments/production/modules/profile/manifests/builder.pp, line: 30)
Notice: /Stage[main]/Profile::Builder/File[/usr/local/bin/builder-do-update]/ensure: …
Notice: /Stage[main]/Profile::Builder/File[/usr/local/bin/builder-rebuild-all]/ensure: …
Notice: /Stage[main]/Profile::Builder/File[/etc/builder-wordpress-hosts]/ensure: …
…
Notice: /Stage[main]/Systemd/File[/etc/sysusers.d]/ensure: created
Notice: /Stage[main]/Users::Config/Systemd::Sysuser[base-config]/File[/etc/sysusers.d/base-config.conf]/ensure: …
Info: /Stage[main]/Users::Config/Systemd::Sysuser[base-config]/File[/etc/sysusers.d/base-config.conf]: Scheduling refresh of Service[systemd-sysusers]
Error: /Stage[main]/Nftables/Package[nftables]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install nftables' returned 100: Reading package lists...
      Building dependency tree...
      Reading state information...
      Package nftables is not available, but is referred to by another package.
      This may mean that the package is missing, has been obsoleted, or
      is only available from another source
      E: Package 'nftables' has no installation candidate
Notice: /Stage[main]/Nftables/File[/etc/nftables.conf]: Dependency Package[nftables] has failures: true
Warning: /Stage[main]/Nftables/File[/etc/nftables.conf]: Skipping because of failed dependencies
Warning: /Stage[main]/Nftables/File[/etc/nftables/]: Skipping because of failed dependencies
Error: /Stage[main]/Profile::Base/Package[git]/ensure: change from 'purged' to 'present' failed: … : Unable to locate package git
Error: /Stage[main]/Profile::Base/Package[jq]/ensure: change from 'purged' to 'present' failed: … E: Unable to locate package jq
Error: /Stage[main]/Profile::Base/Package[molly-guard]/ensure: change from 'purged' to 'present' failed: … E: Package 'molly-guard' has no installation candidate
Error: /Stage[main]/Profile::Base/Package[tmux]/ensure: change from 'purged' to 'present' failed: … E: Package 'tmux' has no installation candidate
Error: /Stage[main]/Nginx/Package[nginx-full]/ensure: change from 'purged' to 'present' failed: … E: Unable to locate package nginx-full
…
Notice: /Stage[main]/Notifier/Systemd::Sysuser[notifier]/File[/etc/sysusers.d/notifier.conf]/ensure: …
Info: /Stage[main]/Notifier/Systemd::Sysuser[notifier]/File[/etc/sysusers.d/notifier.conf]: Scheduling refresh of Service[systemd-sysusers]
Notice: /Stage[main]/Notifier/Systemd::Sysuser[notifier]/Exec[update-sysusers-notifier]/returns: executed successfully
Notice: /Stage[main]/Notifier/Systemd::Tmpfile[notifier]/File[/etc/tmpfiles.d/notifier.conf]/ensure: …
…
Notice: /Stage[main]/Profile::Builder/Systemd::Sysuser[builder]/Exec[update-sysusers-builder]/returns: executed successfully
Notice: /Stage[main]/Profile::Builder/Git::Clone[builder-api_jquery_com]/File[/srv/builder/api_jquery_com]/ensure: created
Error: /Stage[main]/Profile::Builder/Git::Clone[builder-api_jquery_com]/Exec[git_clone_builder-api_jquery_com]/returns: change from 'notrun' to ['0'] failed: Could not find command '/usr/bin/git'
```

Ref https://github.com/jquery/infrastructure-puppet/issues/91